In [1]:
import sys; sys.path.append("../..")

import pandas as pd
import zipfile

ESCO_ZIP = "ESCO dataset - v1.2.1 - classification - en - csv.zip"


def esco_csv(name, **kwargs):
    """Read one CSV of the ESCO distribution straight out of the zip."""
    with zipfile.ZipFile(ESCO_ZIP) as archive:
        return pd.read_csv(archive.open("ESCO dataset - v1.2.1 - classification - en - csv/" + name), **kwargs)

# Skills

`broaderRelationsSkillPillar_en.csv`: the broader relations between skills. Only the relevant columns are kept.

In [2]:
columns_used = ["conceptUri", "broaderUri"]
skill_rel = esco_csv("broaderRelationsSkillPillar_en.csv", usecols=columns_used)

Strip the common URI prefix from `conceptUri` and `broaderUri`.

In [3]:
for col in skill_rel.columns:
    skill_rel[col] = (
        skill_rel[col]
        .str.replace("http://data.europa.eu/esco/", "", regex=False)
        .str.replace("skill/", "", regex=False)
        .str.replace("isced-f/", "", regex=False)
    )

Save the skill relations.

In [4]:
skill_rel.to_csv("processed/skill_tax.csv", index=False)

# Occupations

`broaderRelationsOccPillar_en.csv`: the broader relations between occupations. Only the relevant columns are kept.

In [5]:
columns_used = ["conceptUri", "broaderUri"]
occ_rel = esco_csv("broaderRelationsOccPillar_en.csv", usecols=columns_used)

Strip the common URI prefix from `conceptUri` and `broaderUri`.

In [6]:
occ_rel

,conceptUri,broaderUri
0,http://data.europa.eu/esco/isco/C01,http://data.europa.eu/esco/isco/C0
1,http://data.europa.eu/esco/isco/C011,http://data.europa.eu/esco/isco/C01
2,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/isco/C011
3,http://data.europa.eu/esco/isco/C02,http://data.europa.eu/esco/isco/C0
4,http://data.europa.eu/esco/isco/C021,http://data.europa.eu/esco/isco/C02
...,...,...
3643,http://data.europa.eu/esco/occupation/ff2c1183...,http://data.europa.eu/esco/occupation/4b05bef2...
3644,http://data.europa.eu/esco/occupation/ff3a164d...,http://data.europa.eu/esco/occupation/14031d4a...
3645,http://data.europa.eu/esco/occupation/ff4c28e2...,http://data.europa.eu/esco/occupation/4fef1907...
3646,http://data.europa.eu/esco/occupation/ff63fa99...,http://data.europa.eu/esco/occupation/bcead4e9...
3647,http://data.europa.eu/esco/occupation/ffa4dd5d...,http://data.europa.eu/esco/occupation/31808988...

In [7]:
for col in occ_rel.columns:
    occ_rel[col] = (
        occ_rel[col]
        .str.replace("http://data.europa.eu/esco/isco/", "", regex=False)
        .str.replace("http://data.europa.eu/esco/occupation/", "", regex=False)
    )

In [8]:
occ_rel

,conceptUri,broaderUri
0,C01,C0
1,C011,C01
2,C0110,C011
3,C02,C0
4,C021,C02
...,...,...
3643,ff2c1183-3fd7-40c7-8ddc-b20b100363c3,4b05bef2-ded4-4b09-ab94-f4c6a555a775
3644,ff3a164d-4045-4511-a472-49093dabf9fc,14031d4a-6e99-442f-b4fe-18262b6432b2
3645,ff4c28e2-66b1-4ae7-9053-fba8ec3428be,4fef1907-cf82-413b-841a-02ef57e299a6
3646,ff63fa99-c634-4e6f-a693-6a49482952e9,bcead4e9-3697-4831-b62e-ddb83d7d469d
3647,ffa4dd5d-702b-4828-ad85-17ec50db6656,31808988-fc0a-4bc3-9e47-27216d6759f5

In [9]:
occ_rel.to_csv("processed/occupation_tax.csv", index=False)

# Skill - Occupation

`occupationSkillRelations_en.csv`: the occupation-skill relations. Only the relevant columns are kept.

In [10]:
columns_used = ["occupationUri", "relationType", "skillUri"]

occskill_rel = esco_csv("occupationSkillRelations_en.csv", usecols=columns_used)

Strip the common URI prefix from `occupationUri` and `skillUri`.

In [11]:
occskill_rel.occupationUri = occskill_rel.occupationUri.apply(
    lambda x: x.replace("http://data.europa.eu/esco/occupation/", "")
)
occskill_rel.skillUri = occskill_rel.skillUri.apply(
    lambda x: x.replace("http://data.europa.eu/esco/skill/", "")
)

Save the occupation-skill relations.

In [12]:
occskill_rel.to_csv("processed/occ_skill_rel.csv", index=False)