In [1]:
import sys; sys.path.append("../..")

import pandas as pd

from kb_graph import taxonomy_levels
import zipfile

ESCO_ZIP = "ESCO dataset - v1.2.1 - classification - en - csv.zip"


def esco_csv(name, **kwargs):
    """Read one CSV of the ESCO distribution straight out of the zip."""
    with zipfile.ZipFile(ESCO_ZIP) as archive:
        return pd.read_csv(archive.open("ESCO dataset - v1.2.1 - classification - en - csv/" + name), **kwargs)

In [2]:
jobs = esco_csv("occupations_en.csv")
isco = esco_csv("ISCOGroups_en.csv")

In [3]:
jobs

,conceptType,conceptUri,iscoGroup,preferredLabel,altLabels,hiddenLabels,status,modifiedDate,regulatedProfessionNote,scopeNote,definition,inScheme,description,code,naceCode
0,Occupation,http://data.europa.eu/esco/occupation/00030d09...,2654,technical director,director of technical arts\ntechnical supervis...,NaN,released,2024-01-25T11:28:50.295Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Technical directors realise the artistic visio...,2654.1.7,http://data.europa.eu/ux2/nace2.1/9031
1,Occupation,http://data.europa.eu/esco/occupation/000e93a3...,8121,metal drawing machine operator,wire drawer\nforming machine operative\ndraw m...,NaN,released,2024-01-23T10:09:32.099Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Metal drawing machine operators set up and ope...,8121.4,http://data.europa.eu/ux2/nace2.1/242
2,Occupation,http://data.europa.eu/esco/occupation/0019b951...,7543,precision device inspector,precision device quality control supervisor\np...,NaN,released,2024-01-25T15:00:12.188Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Precision device inspectors make sure precisio...,7543.10.3,http://data.europa.eu/ux2/nace2.1/2651
3,Occupation,http://data.europa.eu/esco/occupation/0022f466...,3155,air traffic safety technician,air traffic safety electronics hardware specia...,NaN,released,2024-01-29T16:01:13.998Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Air traffic safety technicians provide technic...,3155.1,http://data.europa.eu/ux2/nace2.1/5223
4,Occupation,http://data.europa.eu/esco/occupation/002da35b...,2431,hospitality revenue manager,yield manager\nhospitality yields manager\nhos...,NaN,released,2024-01-11T10:28:45.871Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Hospitality revenue managers maximise revenue ...,2431.9,"http://data.europa.eu/ux2/nace2.1/701,\nhttp:/..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3038,Occupation,http://data.europa.eu/esco/occupation/ff656b3a...,2120,demographer,demographers\ndemography studies scientist\nde...,NaN,released,2024-01-23T10:55:28.923Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Demographers study a variety of parameters rel...,2120.2,http://data.europa.eu/ux2/nace2.1/722
3039,Occupation,http://data.europa.eu/esco/occupation/ff8d4065...,9612,sorter labourer,recycling site sorter labourer\ngrader\ntextil...,NaN,released,2024-01-16T11:18:17.704Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Sorter labourers sort recyclable materials and...,9612.2,http://data.europa.eu/ux2/nace2.1/3821
3040,Occupation,http://data.europa.eu/esco/occupation/ffa4dd5d...,5414,armoured car guard,car escort\narmoured van guard\narmoured car s...,NaN,released,2022-01-13T09:51:50.643Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Armoured car guards ensure the safe transporta...,5414.1.2,http://data.europa.eu/ux2/nace2.1/8001
3041,Occupation,http://data.europa.eu/esco/occupation/ffade2f4...,2422,civil service administrative officer,government administrative officer\nlocal autho...,NaN,released,2024-01-16T14:38:39.909Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Civil service administrative officers perform ...,2422.1,http://data.europa.eu/ux2/nace2.1/8411
3042,Occupation,http://data.europa.eu/esco/occupation/ffc292f1...,8211,motor vehicle assembler,motor vehicle assemblies tester\ncar factory w...,NaN,released,2024-01-26T14:50:33.322Z,http://data.europa.eu/esco/regulated-professio...,NaN,NaN,http://data.europa.eu/esco/concept-scheme/memb...,Motor vehicle assemblers install and put prefa...,8211.5,http://data.europa.eu/ux2/nace2.1/291

In [4]:
isco

,conceptType,conceptUri,code,preferredLabel,status,altLabels,inScheme,description
0,ISCOGroup,http://data.europa.eu/esco/isco/C0,0,Armed forces occupations,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Armed forces occupations include all jobs held...
1,ISCOGroup,http://data.europa.eu/esco/isco/C01,1,Commissioned armed forces officers,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Commissioned armed forces officers provide lea...
2,ISCOGroup,http://data.europa.eu/esco/isco/C011,11,Commissioned armed forces officers,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Commissioned armed forces officers provide lea...
3,ISCOGroup,http://data.europa.eu/esco/isco/C0110,110,Commissioned armed forces officers,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Commissioned armed forces officers provide lea...
4,ISCOGroup,http://data.europa.eu/esco/isco/C02,2,Non-commissioned armed forces officers,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Non-commissioned armed forces officers enforce...
...,...,...,...,...,...,...,...,...
614,ISCOGroup,http://data.europa.eu/esco/isco/C9621,9621,"Messengers, package deliverers and luggage por...",released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,"Messengers, package deliverers and luggage por..."
615,ISCOGroup,http://data.europa.eu/esco/isco/C9622,9622,Odd job persons,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,"Odd-job persons clean, paint and maintain buil..."
616,ISCOGroup,http://data.europa.eu/esco/isco/C9623,9623,Meter readers and vending-machine collectors,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Meter readers and vending-machine collectors s...
617,ISCOGroup,http://data.europa.eu/esco/isco/C9624,9624,Water and firewood collectors,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,Water and firewood collectors collect water an...
618,ISCOGroup,http://data.europa.eu/esco/isco/C9629,9629,Elementary workers not elsewhere classified,released,NaN,http://data.europa.eu/esco/concept-scheme/occu...,This unit group covers elementary workers not ...

In [5]:
jobs = jobs[["conceptUri", "preferredLabel", "altLabels", "code", "description"]]
isco = isco[["conceptUri", "preferredLabel", "altLabels", "description"]]

Strip the common URI prefix from `conceptUri`.

In [6]:
jobs["conceptUri"] = jobs["conceptUri"].apply(
    lambda x: x.replace("http://data.europa.eu/esco/occupation/", "")
)
isco["conceptUri"] = isco["conceptUri"].apply(
    lambda x: x.replace("http://data.europa.eu/esco/isco/", "")
)
jobs = jobs.drop_duplicates("conceptUri")
isco = isco.drop_duplicates("conceptUri")

`altLabels` holds newline-separated alternative labels: split them into a list and give each label an integer id.

In [7]:
jobs["altLabels"] = jobs["altLabels"].apply(
    lambda x: x.split("\n") if isinstance(x, str) else []
)
isco["altLabels"] = isco["altLabels"].apply(
    lambda x: x.split("\n") if isinstance(x, str) else []
)

In [8]:
alt_label2id = (
    pd.concat([jobs["altLabels"].explode(), isco["altLabels"].explode()])
    .drop_duplicates()
    .reset_index(drop=True)
    .reset_index()
    .set_index("altLabels")
    .to_dict()["index"]
)

Replace the alternative labels in `altLabels` with their ids.

In [9]:
jobs["altLabels"] = jobs["altLabels"].apply(lambda x: [alt_label2id[i] for i in x])
isco["altLabels"] = isco["altLabels"].apply(lambda x: [alt_label2id[i] for i in x])

Rename the columns.

In [10]:
jobs = jobs.rename(
    columns={
        "conceptUri": "occ_id",
        "preferredLabel": "label",
    }
).set_index("occ_id")

isco = isco.rename(
    columns={
        "conceptUri": "occ_id",
        "preferredLabel": "label",
    }
).set_index("occ_id")

# ISCOGroups_en.csv has a `code` column, but it holds the digits without the pillar
# letter, so the armed forces (1, 11, 110) collide with Managers (1, 11, 110). The id
# derived from the URI is the only unambiguous code these groups have.
isco["code"] = isco.index

Save the occupations and the alternative labels.

In [11]:
(pd
 .DataFrame
 .from_dict(alt_label2id, orient="index")
 .reset_index()
 .rename(columns={"index": "alt_label", 0: "alt_label_id"})
 .to_csv("processed/occ_alt_labels.csv", index=False)
 )

In [12]:
jobs

,label,altLabels,code,description
occ_id,,,,
00030d09-2b3a-4efd-87cc-c4ea39d27c34,technical director,"[0, 1, 2, 3, 4, 5]",2654.1.7,Technical directors realise the artistic visio...
000e93a3-d956-4e45-aacb-f12c83fedf84,metal drawing machine operator,"[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]",8121.4,Metal drawing machine operators set up and ope...
0019b951-c699-4191-8208-9822882d150c,precision device inspector,"[17, 18, 19, 20, 21, 22, 23, 24, 25, 26]",7543.10.3,Precision device inspectors make sure precisio...
0022f466-426c-41a4-ac96-a235c945cf97,air traffic safety technician,"[27, 28, 29, 30, 31, 32, 33]",3155.1,Air traffic safety technicians provide technic...
002da35b-7808-43f3-83bf-63596b8b351f,hospitality revenue manager,"[34, 35, 36, 37]",2431.9,Hospitality revenue managers maximise revenue ...
...,...,...,...,...
ff656b3a-65a8-4b4f-b04e-9db12936519b,demographer,"[29440, 29441, 29442, 29443, 29444, 29445, 294...",2120.2,Demographers study a variety of parameters rel...
ff8d4065-db44-47c7-a4bd-51b3c306ef70,sorter labourer,"[29455, 24561, 29456, 29457, 24412, 29458, 294...",9612.2,Sorter labourers sort recyclable materials and...
ffa4dd5d-702b-4828-ad85-17ec50db6656,armoured car guard,"[29466, 29467, 29468, 29469, 29470, 29471, 294...",5414.1.2,Armoured car guards ensure the safe transporta...
ffade2f4-2528-4dfd-b36a-6e4092be08ed,civil service administrative officer,"[9738, 29476, 29477]",2422.1,Civil service administrative officers perform ...
ffc292f1-89e2-4406-8eff-39096c94e731,motor vehicle assembler,"[29478, 29479, 29480, 29481, 29482, 29483, 294...",8211.5,Motor vehicle assemblers install and put prefa...

In [13]:
# One digit per ISCO level: C1 -> 1, C11 -> 2, C0110 -> 4.
isco["level"] = [len(occ_id) - 1 for occ_id in isco.index]

In [14]:
# Shortest distance from a taxonomy root, plus "has no narrower concept".
level, leaf = taxonomy_levels(pd.read_csv("processed/occupation_tax.csv"))

In [15]:
# Indexing, not .map: an occupation outside the taxonomy raises here.
jobs["level"] = [level[occ_id] for occ_id in jobs.index]
jobs["leaf"] = [leaf[occ_id] for occ_id in jobs.index]
isco["leaf"] = [leaf[occ_id] for occ_id in isco.index]

In [16]:
# The armed-forces groups (C01, C011, C0110, C02, ...) take their id from the URI; their
# `code` would collide with Managers, Professionals and Technicians.
jobs = pd.concat([jobs, isco], axis=0)[["label", "altLabels", "code", "leaf", "level", "description"]]
assert jobs.index.is_unique, f"duplicate occ_id: {sorted(set(jobs.index[jobs.index.duplicated()]))}"

In [17]:
jobs

,label,altLabels,code,leaf,level,description
occ_id,,,,,,
00030d09-2b3a-4efd-87cc-c4ea39d27c34,technical director,"[0, 1, 2, 3, 4, 5]",2654.1.7,True,6,Technical directors realise the artistic visio...
000e93a3-d956-4e45-aacb-f12c83fedf84,metal drawing machine operator,"[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]",8121.4,True,5,Metal drawing machine operators set up and ope...
0019b951-c699-4191-8208-9822882d150c,precision device inspector,"[17, 18, 19, 20, 21, 22, 23, 24, 25, 26]",7543.10.3,True,6,Precision device inspectors make sure precisio...
0022f466-426c-41a4-ac96-a235c945cf97,air traffic safety technician,"[27, 28, 29, 30, 31, 32, 33]",3155.1,True,5,Air traffic safety technicians provide technic...
002da35b-7808-43f3-83bf-63596b8b351f,hospitality revenue manager,"[34, 35, 36, 37]",2431.9,True,5,Hospitality revenue managers maximise revenue ...
...,...,...,...,...,...,...
C9621,"Messengers, package deliverers and luggage por...",[],C9621,False,4,"Messengers, package deliverers and luggage por..."
C9622,Odd job persons,[],C9622,False,4,"Odd-job persons clean, paint and maintain buil..."
C9623,Meter readers and vending-machine collectors,[],C9623,False,4,Meter readers and vending-machine collectors s...
C9624,Water and firewood collectors,[],C9624,True,4,Water and firewood collectors collect water an...
C9629,Elementary workers not elsewhere classified,[],C9629,False,4,This unit group covers elementary workers not ...

In [18]:
jobs.to_csv("processed/occupations.csv")